[package]
name = "godot"
version = "0.1.0"
edition = "2021"
rust-version = "1.63"

[features]
default = ["convenience"]
trace = ["godot-core/trace"]
convenience = []
codegen-fmt = ["godot-core/codegen-fmt"]
minimal = ["godot-core/minimal"]

[dependencies]
godot-core = { path = "../godot-core" }
godot-macros = { path = "../godot-macros" }

[dev-dependencies]
godot-core = { path = "../godot-core", features = ["unit-test"] }