[package]
name = "godot-ffi"
version = "0.1.0"
edition = "2021"
rust-version = "1.63"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
codegen-fmt = ["godot-codegen/codegen-fmt"]
minimal = ["godot-codegen/minimal"]
codegen-disabled = ["godot-codegen/codegen-disabled"]

[dependencies]
paste = "1"

[build-dependencies]
bindgen = { version = "0.63.0", default-features = false, features = ["runtime"] }
godot-codegen = { path = "../godot-codegen" }
